;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #1F1F1F
foreground = #FFFFFF
foreground-alt = #FFFFFF

;; shades
;; shade1 = #263238
;; shade2 = #37474F
;; shade3 = #455A64
;; shade4 = #546E7A
;; shade5 = #607D8B
;; shade6 = #78909C
;; shade7 = #90A4AE
;; shade8 = #B0BEC5
shade1 = #011814
shade2 = #03483C
shade3 = #067864
shade4 = #08A88C
shade5 = #0BD9B4
shade6 = #23F3CE
shade7 = #53F6D9
shade8 = #83F8E4


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
